New failure-inducing case
Caused by pair of brackets inside name of link

There was 1 failure:
1) lab5test(MarkdownParseTest)
array lengths differed, expected.length=1 actual.length=0; arrays first differed at element [0]; expected:<something.com> but was:<end of array>